### ISSUE TITLE
Uncaught TypeError: Cannot read property 'EventPluginHub' of undefined

### ISSUE THREAD

**Issue by omrihaim** [ctxhou/react-tabtab#100]
Hey.

I've just tried the examples of basic tabs view and draggable ones, and got the following error, with no real ability to change it as the stack is inside the package: 

Uncaught TypeError: Cannot read property 'EventPluginHub' of undefined

Uncaught TypeError: Cannot read property 'EventPluginHub' of undefined
    at injectTapEventPlugin 
    at Object.<anonymous> 
    at __webpack_require__ 
    at Object._typeof 
    at __webpack_require__ 
    at Object.defineProperty.value 
    at __webpack_require__ 
    at Object.defineProperty.value 
    at __webpack_require__ 
    at Object._typeof 

Issues were solved when I've commented out the tabs components.

**Comment by ctxhou** [comment]
Hi @omrihaim,

Could you show me more example of your code?

I've tried the basic example on codesandbox and it works.

[https://codesandbox.io/s/24nr07p3jr](https://codesandbox.io/s/24nr07p3jr)
