### ISSUE TITLE
custom style not working

### ISSUE THREAD

**Issue by prodigylabs** [ctxhou/react-tabtab#101]
If i add custom style as follows

import * as customStyle from 'react-tabtab/lib/themes/bootstrap';

This works fine.

However, if i create my own style  following instructions and put into themes/index.js. Import as follows

import * as customStyle from '../themes';

Then it does not work. Not work meaning the styles are not picked up from my index.js, there are no errors either.

My index.js is exact copy of https://github.com/ctxhou/react-tabtab/tree/master/src/themes/bootstrap

**Comment by ctxhou** [comment]
Hi @prodigylabs 
Could you paste your copy code to let me know more?

Do you change [this line](https://github.com/ctxhou/react-tabtab/blob/master/src/themes/bootstrap/index.js#L1) to `import {styled} from 'react-tabtab'`?
