### ISSUE TITLE
TabList: Initiate scroll on componentDidMount when defaultIndex is set

### ISSUE THREAD

**Issue by fdidron** [ctxhou/react-tabtab#102]
Hi,

Thanks for the really great plugin.

One slight issue I'm having is that when I mount the Tabs component with the prop `defaultIndex` set to the index of a Tab hidden by the container, it doesn't scroll to make it visible.

I tried to add the following code `this.scrolltoIndex(this.props.activeIndex)` in the `componentDidMount` method of the  `TabList` component., it seems to be scrolling a little, but not enough to show the active tab, I'm suspecting an issue with the container width calcuation.

**Comment by ctxhou** [comment]
Hi @fdidron 
I will check the mounted width calculation.

Thanks for the report.

**Comment by ctxhou** [comment]
fix at #105
