### ISSUE TITLE
Make your own style

### ISSUE THREAD

**Issue by PeterS86** [ctxhou/react-tabtab#124]
Hey guys,

I want to create an own style. Unfortunately it does not work.
Would be great, if you can share an example...

Thanks in advance

**Comment by kjkjjang-gmail** [comment]
Write sample code in my blog.
I wrote it in Korean but can read it.
[react-tabtab-customStyle](https://kjkjjang.wordpress.com/2019/07/08/reacttypescript-모듈-추가-react-tabtab-2편/)

**Comment by adamcanray** [comment]
Have you solved this problem? If I already have a problem similar to yours. if I may ask for an example.
@PeterS86

**Comment by PeterS86** [comment]
Unfortunately I don't solved this.
