### ISSUE TITLE
custom styled is not function

### ISSUE THREAD

**Issue by yonghuay** [ctxhou/react-tabtab#127]
I followed the guidelines in order to make my own style, However, I am getting the following error: **TypeError: (0 , _reactTabtab2.default) is not a function**
import {styled} from 'react-tabtab';
let {TabListStyle, ActionButtonStyle, TabStyle, PanelStyle} = styled;

TabListStyle = styled(TabListStyle)`
  // write css
`;

In order to fix the issue. I have to write like the following: 
**import styled from 'styled-components';
import {styled as themeStyled} from 'react-tabtab';
let {TabListStyle, ActionButtonStyle, TabStyle, PanelStyle} = themeStyled;**

TabListStyle = styled(TabListStyle)`
  // write css
`;

"react": "^16.8.6", "react-dom": "^16.8.6", "styled-components": "^4.0.0" "react-tabtab": "^2.0.0",

**Comment by Conowa** [comment]
Here is a working example that might help you:
https://kjkjjang.wordpress.com/2019/07/08/reacttypescript-%EB%AA%A8%EB%93%88-%EC%B6%94%EA%B0%80-react-tabtab-2%ED%8E%B8/

**Comment by yonghuay** [comment]
> Here is a working example that might help you:
> https://kjkjjang.wordpress.com/2019/07/08/reacttypescript-%EB%AA%A8%EB%93%88-%EC%B6%94%EA%B0%80-react-tabtab-2%ED%8E%B8/

Thanks, This helps me a lot.
