### ISSUE TITLE
Object styled is not a function

### ISSUE THREAD

**Issue by pedrobernardina** [ctxhou/react-tabtab#148]
This issue is related to #127 

It's clear how to make the code work, but the documentation hasn't been updated.

**Comment by ctxhou** [comment]
@pedrobernardina thanks for reporting. Would you mind polish the document in your convenience?

**Comment by pedrobernardina** [comment]
Done it! 

First time contributing, hope everything is right :)

**Comment by ctxhou** [comment]
@pedrobernardina thanks a lot!! looks great!
