### ISSUE TITLE
Delete button does not appear on every tab

### ISSUE THREAD

**Issue by kingaiakab** [ctxhou/react-tabtab#71]
Shouldn't `tabDeleteButton` property make `tabtab__folder__circCont` visible on each tab? It is only visible on the active one.

**Comment by erica93k** [comment]
From your README:

> tabDeleteButton: whether each tab show delete button

**Comment by ctxhou** [comment]
Hi @kingaiakab, react-tabtab `v1` has redesigned api and added new features.
You can try new version now! 🍻
