### ISSUE TITLE
Performance issues, with unnecessary updates

### ISSUE THREAD

**Issue by mathiasjakobsen** [ctxhou/react-tabtab#73]
Thank you for this awesome package! It's really great, and works as expected and without any hassle. My only concern is a lot of unnecessary updates, originating from `react-tabtab` components. I use the `why-did-you-update` package, to monitor updates that could be avoided, since props and/or state are the same.

![skaermbillede 2017-12-07 kl 13 05 49](https://user-images.githubusercontent.com/1573748/33714504-75608400-db4f-11e7-8c71-faf28a522cdf.png)

Any ideas on how to avoid this?

**Comment by ctxhou** [comment]
Yep, that's right.
This is the issue I am working on now.
I will report you when I finish.
Thanks for the report.

**Comment by mathiasjakobsen** [comment]
Awesome! Keep up the good work, @ctxhou 🚀

**Comment by ctxhou** [comment]
Hi @mathiasjakobsen, you can try version `1.0.0-rc.3`.
I've fix the performance issue.

**Comment by mathiasjakobsen** [comment]
@ctxhou I still gets some warnings on `sortableList` and `DragTabList` ⛄️ But there is definitely improvements in `rc3` 👍 

![skaermbillede 2017-12-11 kl 10 44 57](https://user-images.githubusercontent.com/1573748/33824986-6e17f08e-de60-11e7-9d93-315774edb19f.png)

**Comment by ctxhou** [comment]
@mathiasjakobsen, thanks for your patience.
react-tabtab is shipping to `v1`. And the performance issue is also fixed in this version! 🍺

**Comment by mathiasjakobsen** [comment]
@ctxhou awesome! 🍻
