### ISSUE TITLE
Font face changes while dragging in the demo

### ISSUE THREAD

**Issue by mrozbarry** [ctxhou/react-tabtab#76]
Not sure if that's an OS, browser, or library limitation. Most of my DnD apps drag images, so I've never noticed it before if it's OS or browser.

**Comment by ctxhou** [comment]
@mrozbarry Can you provide your OS and browser to help me debug?

**Comment by ctxhou** [comment]
Alright, I find the bug at safari. I'll fix it soon. Thanks!
