### ISSUE TITLE
Draggable on touch device

### ISSUE THREAD

**Issue by loopmode** [ctxhou/react-tabtab#89]
Draggable tabs not working on touch devices. Can be reproduced with Chrome device simulator.

**Comment by ctxhou** [comment]
Hi @loopmode 
Thanks for your report.
I found this problem after your report. I don't know why it cannot work on Chrome devtool, although it can work well on mobile device.

Do you know the possible problem?

**Comment by loopmode** [comment]
Hi
Uh, unfortunately I have no idea. I just tried it out on my phone when I saw the link on echojs.com.
In case I find the time, I'll check out the code and try locally, but no promises.. :) lot's of problems to solve at work

**Comment by ctxhou** [comment]
Yeah, thank you.
Do you mean the dnd also doesn't work on your phone?

**Comment by loopmode** [comment]
Yes, exactly. Samsung A8 with Chrome 66

**Comment by ctxhou** [comment]
Hi @loopmode 
I think I found the problems.
Could you try the demo again? https://ctxhou.github.io/react-tabtab/

**Comment by loopmode** [comment]
Well.. It's still shaky and flaky, but it's better!
I see in the chrome devtools it works fine.
On my Samsung A8 however, it worked like 1 time out of 20, and 19 times the "copy/cut/select text dialog" popped up and broke things.
I guess you could try and disable text selection on the tab headers: https://www.w3schools.com/cssref/css3_pr_user-select.asp

**Comment by loopmode** [comment]
BTW that's exactly it: if I touch inside the header but outside the text, I can drag correctly. But if I touch inside the text, it doesn't because if context menu popup.
