### ISSUE TITLE
How to set the height and width of PanelList ?

### ISSUE THREAD

**Issue by aiic03** [ctxhou/react-tabtab#91]
Since we're using Draggable Tab to display dynamic content , we expect all tabs to have a fixed height and width （80vh, 100vw for example）

However setting style seperately for every Panel content is not working.

![picture](https://user-images.githubusercontent.com/11695765/39564055-31ad0db4-4ee5-11e8-8079-114356f7acce.png)

Any help will be appreciated.

**Comment by ctxhou** [comment]
Hi @aiic03 
You can reference this [example](https://codesandbox.io/s/1zw80yjm9j)
I think we need to write more document about how to customize the style.
Feel free to let me know if you have other questions.

**Comment by aiic03** [comment]
Thank you. The example above works.
