### ISSUE TITLE
`closable` not working when `ExtraButton` is set

### ISSUE THREAD

**Issue by aiic03** [ctxhou/react-tabtab#92]
From official samples[[here](https://ctxhou.github.io/react-tabtab/#complicated)], I found that when `ExtraButton` was set, `closable` could not work properly. 

Here are some code revealing the problem. https://codesandbox.io/s/vvnkr7p50y

Only when `ExtraButton` is removed, `closable` starts to work.

Is this a bug or an usage issue ?

**Comment by ctxhou** [comment]
Hi @aiic03, thanks for the report.
I've fixed it on pr #94, and you can reference the note.

Please update to latest version.
